### PR TITLE
Upgrade James ElasticSearch version

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by mbaechler** [comment]
:+1:

**Comment by fvn-linagora** [comment]
:+1: 
Mais c'est quoi bitHound ?

**Comment by heroandtn3** [comment]
It seems that Benoit already have a same PR: https://ci.open-paas.org/stash/projects/OR/repos/rse/pull-requests/2127/overview

**Comment by chamerling** [comment]
We do PR on stash, not on github

**Pull request closed without merging**
