### PR TITLE
replace OpenPaas to OpendPaaS

### PR DESCRIPTION
**Pull request by hoangofHUST**

### CODE REVIEW

**Comment by heroandtn3** [comment]
LGTM

**Comment by MichaelBailly** [comment]
Thank you for that first contribution to OpenPaaS @hoangofHUST ! :muscle:

**Comment by tuanlc** [comment]
@hoangofHUST There are a lot of conflicts. Can you resolve them, please?

**Comment by tuanlc** [comment]
I close this PR because there is no more feedback from the creator to resolve conflict to merge.

**Pull request closed without merging**
