### PR TITLE
fixes an exception when searching contacts

### PR DESCRIPTION
**Pull request by sieira**
The exception occurs because the offset for the pagination was being calculated with a NaN, resulting in a NaN result. The previous implementation checked whether the page was defined, but didn't consider if it was not a number

### CODE REVIEW

**Comment by sieira** [comment]
Related with this ticket: https://ci.open-paas.org/jira/browse/OR-1649

**Comment by MarioArnt** [comment]
Hi Luis, a fix for this problem has just been merged.
https://ci.open-paas.org/stash/projects/OR/repos/rse/pull-requests/1207/overview
Consequently, the page should not be NaN any more.
However, your solution is interesting and can be also added

**Comment by sieira** [comment]
I was encountering this exception with the last head on github

(fbaf9d3c1a57c5121aaac100d254812bcccac65d Tue Sep 1 14:43:53 2015)

Well, then it's up to you

**Comment by ddolcimascolo** [comment]
Hi Luis,

Thanks for your contribution, but we merged another fix some times ago that fixes this issue.

Regards,

**Pull request closed without merging**
